name: Minecraft Server 1.16.5 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up Java 16
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '16'

      # Step 3: Install dependencies
      - run: sudo apt-get update && sudo apt-get install -y git wget zip

      # Step 4: Download BuildTools
      - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar

      # Step 5: Build Spigot 1.16.5
      - run: java -jar BuildTools.jar --rev 1.16.5

      # Step 6: Accept EULA
      - run: echo "eula=true" > eula.txt

      # Step 7: Start Spigot server in a loop and save artifacts every 30 mins
      - name: Start Server with Periodic Backups
        run: |
          mkdir -p backups
          while true; do
            java -Xms2G -Xmx4G -jar spigot-1.16.5.jar nogui &
            SERVER_PID=$!
            # Wait 30 minutes
            sleep 1800
            # Backup worlds and jar
            zip -r backups/worlds_backup_$(date +%
            
