name: Minecraft Server 1.16.5 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up Java 16
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '16'

      # Step 3: Install dependencies
      - run: sudo apt-get update && sudo apt-get install -y git wget zip

      # Step 4: Download BuildTools
      - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar

      # Step 5: Build Spigot 1.16.5
      - run: java -jar BuildTools.jar --rev 1.16.5

      # Step 6: Accept EULA
      - run: echo "eula=true" > eula.txt

      # Step 7: Start server and backup every 30 minutes
      - name: Start Server with Periodic Backups
        run: |
          #!/bin/bash
          mkdir -p backups
          # Run server for up to 6 hours
          END=$((SECONDS+21600))
          while [ $SECONDS -lt $END ]; do
            echo "Starting server..."
            java -Xms2G -Xmx4G -jar spigot-1.16.5.jar nogui &
            SERVER_PID=$!
            
            # Backup loop every 30 minutes
            for i in {1..12}; do
              sleep 1800
              BACKUP_NAME="backups/world_backup_$(date +%s).zip"
              zip -r "$BACKUP_NAME" world spigot-1.16.5.jar
              echo "Backup saved: $BACKUP_NAME"
            done
            
            # Stop server after backups
            kill $SERVER_PID
            wait $SERVER_PID 2>/dev/null
          done

      # Step 8: Upload backups as artifacts
      - name: Upload Backups
        uses: actions/upload-artifact@v3
        with:
          name: spigot-backups
          path: backups/
          
